<?php

namespace App\Enums;

enum TipoNotificacion: string
{
    case NUEVA_POSTULACION      = 'NUEVA_POSTULACION';
    case POSTULACION_RETIRADA   = 'POSTULACION_RETIRADA';
    case VOLUNTARIO_ASISTIO     = 'VOLUNTARIO_ASISTIO';
    case VOLUNTARIO_NO_ASISTIO  = 'VOLUNTARIO_NO_ASISTIO';
    case POSTULACION_ACEPTADA   = 'POSTULACION_ACEPTADA';
    case POSTULACION_RECHAZADA  = 'POSTULACION_RECHAZADA';
    case ACTIVIDAD_CANCELADA    = 'ACTIVIDAD_CANCELADA';
    case ACTIVIDAD_MODIFICADA   = 'ACTIVIDAD_MODIFICADA';
    case FUNDACION_APROBADA     = 'FUNDACION_APROBADA';
    case FUNDACION_RECHAZADA    = 'FUNDACION_RECHAZADA';
    case FUNDACION_SUSPENDIDA   = 'FUNDACION_SUSPENDIDA';
    case FUNDACION_REACTIVADA   = 'FUNDACION_REACTIVADA';
    case RECORDATORIO_ACTIVIDAD = 'RECORDATORIO_ACTIVIDAD';
}
